"""initial migration

Revision ID: bffe1536b069
Revises: None
Create Date: 2016-04-17 12:40:26.779000

"""

# revision identifiers, used by Alembic.
revision = 'bffe1536b069'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('keywords', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('timestamp', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_department'), 'document', ['department'], unique=False)
    op.create_index(op.f('ix_document_keywords'), 'document', ['keywords'], unique=False)
    op.create_index(op.f('ix_document_title'), 'document', ['title'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_title'), table_name='document')
    op.drop_index(op.f('ix_document_keywords'), table_name='document')
    op.drop_index(op.f('ix_document_department'), table_name='document')
    op.drop_table('document')
    op.drop_table('users')
    ### end Alembic commands ###
